direktiv/direktiv-ui

- src/components/modal/index.js
- src/components/navbar/index.js
- src/layouts/events/index.js
- src/layouts/explorer/workflow/index.js
- src/layouts/explorer/workflow/pod.js
- src/layouts/explorer/workflow/revision.js
- src/layouts/explorer/workflow/revisionTab.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/global-services/index.js
- src/layouts/global-services/pod.js
- src/layouts/global-services/revisions.js
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- src/layouts/jqplayground/index.js
- src/layouts/monitoring/index.js
- src/layouts/namespace-services/index.js
- src/layouts/namespace-services/pod.js
- src/layouts/namespace-services/revisions.js
> icons updated

- src/layouts/explorer/workflow/index.js
> Closes #224

- src/layouts/events/index.js
- src/layouts/events/style.css
> events content

- src/layouts/explorer/workflow/index.js
- src/layouts/instance/index.js
- src/layouts/instances/index.js
> Display cancelled instances as Cancelled, not Failed

- package.json
- src/layouts/explorer/workflow/index.js
- src/layouts/namespace-services/index.js
- yarn.lock
Redeploy service button added to workflow services. This button deletes a wf service so it can be redployed next action call.
> Redeploy service button

- package.json
- src/components/modal/index.js
- src/components/navbar/index.js
- src/components/tabs/index.js
- src/layouts/explorer/index.js
- src/layouts/explorer/workflow/index.js
- src/layouts/explorer/workflow/revisionTab.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/global-registries/index.js
- src/layouts/global-services/revisions.js
- src/layouts/namespace-services/index.js
- src/layouts/namespace-services/revisions.js
- src/layouts/settings/registries-panel/index.js
- src/layouts/settings/secrets-panel/index.js
- src/layouts/settings/variables-panel/index.js
- yarn.lock
Adds global validation to modal forms
> Global validation Added

- package.json
- yarn.lock
> upgrade dev-tools

- package.json
- src/layouts/instance/index.js
- yarn.lock
…vent crashing.
Fixes: https://github.com/direktiv/direktiv-ui/issues/250
> Instance Page will adjust if parent wf revision does not exist

- package.json
- src/layouts/explorer/index.js
- src/layouts/global-services/revisions.js
- src/layouts/instance/index.js
- src/layouts/main/index.js
- src/layouts/namespace-services/revisions.js
- src/layouts/notfound/index.js
- src/layouts/notfound/style.css
- yarn.lock
Fixes: https://github.com/direktiv/direktiv-ui/issues/249
> Adds 404 page

- src/layouts/explorer/index.js
Fixes https://github.com/direktiv/direktiv-ui/issues/252
> Search queries added for explorer list

- src/components/tabs/index.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/global-services/revisions.js
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- src/layouts/namespace-services/revisions.js
- src/layouts/notfound/index.js
- src/layouts/settings/secrets-panel/index.js
> fix warnings

- package.json
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- yarn.lock
> instance workflow componenets fixed for routed instances

- src/layouts/instance/index.js
Pretty prints the input in the instance page. Close #270
> Closes #270

- package.json
- src/layouts/explorer/index.js
- yarn.lock
Direktiv-react-hooks updated to include fix that fixes strange behavior when navigating explorer.
> hooks updated

- package.json
- src/components/pagination/index.js
- src/components/pagination/style.css
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- src/layouts/instances/style.css
- yarn.lock
Filtering Added for Instance List
> Filtering Added for Instance List

- src/components/diagram/index.js
- src/components/editor/index.js
- src/layouts/explorer/index.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- src/layouts/settings/variables-panel/index.js
Fixes https://github.com/direktiv/direktiv/issues/542
> Variables tip added to show long names

- src/components/navbar/index.js
Fixes https://github.com/direktiv/direktiv/issues/533
> namespace mirror form now reset inputs on modal close

- src/layouts/explorer/workflow/variables.js
- src/layouts/settings/variables-panel/index.js
Fixes https://github.com/direktiv/direktiv/issues/537
> Overflow for new variable modal fixed

- src/App.css
- src/components/flexbox/style.css
- src/components/navbar/index.js
- src/layouts/explorer/index.js
- src/layouts/mirror/index.js
- src/layouts/mirror/info.js
- src/layouts/mirror/style.css
Fixes https://github.com/direktiv/direktiv/issues/541
> Public and Private Key textarea elements size increased

- src/App.css
- src/components/navbar/index.js
- src/layouts/explorer/index.js
- src/layouts/mirror/info.js
- src/layouts/mirror/style.css
UX Improvements
* Placeholder text updated to be more informative
* Forms display which fields are required
* Tooltips added to better describe each form
* Namespace and Directory Forms redesigned to include input names. 
Enhancements:
* Can now upload file to populate public key or private key textarea
Fixes https://github.com/direktiv/direktiv/issues/545
Fixes: https://github.com/direktiv/direktiv/issues/534
> Improvements to UX of git related ui and Upload option added for public and private key.

- package.json
- src/layouts/explorer/workflow/variables.js
- src/layouts/settings/variables-panel/index.js
- yarn.lock
Related Hook Commit: https://github.com/direktiv/direktiv-react-hooks/commit/7305404171d62200c881849b0b8fb2e999c20b54
Fixes https://github.com/direktiv/direktiv/issues/555
> Pagination added to variable list components

- src/components/namespace-selector/index.js
- src/components/navbar/index.js
- src/layouts/explorer/index.js
- src/layouts/mirror/info.js
Fixes https://github.com/direktiv/direktiv/issues/563
Fixes https://github.com/direktiv/direktiv/issues/535
> Support for 'SSH Keys', 'Access Token' and 'None' Authentication methods have been added

- src/components/flexbox/index.js
- src/components/help/index.js
- src/components/namespace-selector/index.js
- src/components/namespace-selector/style.css
- src/components/navbar/index.js
- src/util/index.js
Fixes https://github.com/direktiv/direktiv-ui/issues/292
Fixes https://github.com/direktiv/direktiv/issues/562
Fixes https://github.com/direktiv/direktiv-ui/issues/286
> Namespace column fixes 

- src/App.css
- src/layouts/mirror/index.js
Fixes https://github.com/direktiv/direktiv/issues/551
> ReadOnly Badge updated to look different to buttons

- package.json
- src/App.css
- src/components/hide-show/index.js
- src/components/hide-show/style.css
- src/components/navbar/index.js
- src/layouts/explorer/index.js
- src/layouts/mirror/info.js
- yarn.lock
UX Fixes:
- Hide and show passphrase
- Show if Public Key, Private Key and Passphrase are set remotely
- Show if token is set remotely
- Git components are now more responsive on small screen size
- Pending Changes modal now has some text that explains to the user that a field will be deleted remotely if a empty string is being sent
Functionality Fixes:
- Fixed token not being set when creating mirror ns/dir with Access Token auth
Fixes: https://github.com/direktiv/direktiv/issues/550
> Adds Better UX for Git Fields: Public Key, Private and Passphrase in all forms

- src/components/diagram-editor/index.js
- src/layouts/instance/index.js
- src/layouts/mirror/logs.js
- src/layouts/monitoring/index.js
- src/layouts/namespace-services/pod.js
Fixes https://github.com/direktiv/direktiv-ui/issues/295
> Better behaviour when disabling auto-scroll on lists

- package.json
- src/App.css
- src/components/button/index.js
- src/components/diagram-editor/import.js
- src/components/diagram-editor/index.js
- src/components/diagram/index.js
- src/components/invalid-workflow/index.js
- src/components/sankey/index.js
- src/layouts/explorer/index.js
- src/layouts/explorer/workflow/index.js
- src/layouts/explorer/workflow/revisionTab.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/instance/index.js
- src/layouts/instances/index.js
- src/layouts/mirror/activities.js
- src/layouts/mirror/info.js
- src/layouts/monitoring/index.js
- src/layouts/settings/variables-panel/index.js
- src/util/responsive.css
- yarn.lock
Cleans up remaining issues on this repository.
* Fixes https://github.com/direktiv/direktiv-ui/issues/289
* Fixes https://github.com/direktiv/direktiv-ui/issues/287
* Fixes https://github.com/direktiv/direktiv-ui/issues/285
* Fixes https://github.com/direktiv/direktiv-ui/issues/284
* Fixes https://github.com/direktiv/direktiv-ui/issues/271
Apart from fixing these issues this pr also contains these changes:
* CSS opacity update from percentage format to scalar
* Complexity reduced on revisions view
> Issue clean up

- src/App.css
- src/components/button/index.js
- src/components/button/style.css
- src/components/diagram-editor/index.js
- src/components/navbar/index.js
- src/layouts/events/index.js
- src/layouts/explorer/index.js
- src/layouts/explorer/workflow/index.js
- src/layouts/explorer/workflow/revisionTab.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/global-registries/index.js
- src/layouts/global-services/index.js
- src/layouts/global-services/revisions.js
- src/layouts/instance/index.js
- src/layouts/jqplayground/index.js
- src/layouts/mirror/activities.js
- src/layouts/mirror/index.js
- src/layouts/mirror/info.js
- src/layouts/mirror/logs.js
- src/layouts/monitoring/index.js
- src/layouts/namespace-services/index.js
- src/layouts/namespace-services/pod.js
- src/layouts/namespace-services/revisions.js
- src/layouts/settings/registries-panel/index.js
- src/layouts/settings/secrets-panel/index.js
- src/layouts/settings/secrets-panel/style.css
- src/layouts/settings/variables-panel/index.js
This PR:
* Standardizes Button component
* Exposes loading and disabled variants as props
* Adds support for disabled buttons having tips and custom cursor
* Non-standard classes in App.css have been migrated to button/style.css or removed
* Usage of non-standard classes from App.css have been updated to use Button Component instead.
> Button component standardized to be used universally

- src/layouts/explorer/workflow/index.js
Fixes https://github.com/direktiv/direktiv/issues/601
> Undo button updated to be more useable

- package.json
- yarn.lock
Fixes https://github.com/direktiv/direktiv/issues/595
> Workflow templates updated

- src/layouts/events/index.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/instances/style.css
- src/layouts/settings/secrets-panel/style.css
- src/layouts/settings/variables-panel/index.js
- src/layouts/settings/variables-panel/style.css
Fixes https://github.com/direktiv/direktiv/issues/569
> Table rows now highlight on hover

- src/components/button/style.css
- src/components/editor/index.js
- src/layouts/mirror/index.js
Fixes https://github.com/direktiv/direktiv/issues/591
> Sync button disabled when mirror is writable and tips added

- src/layouts/explorer/index.js
- src/layouts/explorer/workflow/variables.js
- src/layouts/settings/variables-panel/index.js
Fixes https://github.com/direktiv/direktiv/issues/572
Additionally a setTimeout was added to slowdown how frequently to create new event-stream connections in the searchbar
> Search bar added to variable lists, and throttle added to search bar

- src/components/diagram-editor/import.js
- src/components/diagram-editor/nodes.js
- src/components/diagram-editor/util.js
Closes https://github.com/direktiv/direktiv/issues/625
> Automatically upgrade old state types

- src/layouts/explorer/index.js
Fixes https://github.com/direktiv/direktiv/issues/657
> Loading feedback on explorer nodes when switching namespaces

- package.json
- src/App.js
- yarn.lock
https://github.com/direktiv/direktiv/issues/667
https://github.com/direktiv/direktiv-ui/pull/324
https://github.com/direktiv/direktiv-react-hooks/pull/19
https://github.com/direktiv/direktiv/pull/668
https://github.com/direktiv/direktiv-charts/pull/25
> Login updated to authenticate with direktiv-token header

- package.json
- src/design/Slider/index.stories.tsx
- src/design/Slider/index.tsx
- yarn.lock
> Slider Component

- package.json
- src/design/Popover/index.stories.tsx
- src/design/Popover/index.tsx
- yarn.lock
> Popover component

- src/design/TextArea/index.stories.tsx
- src/design/TextArea/index.tsx
> TextArea component

- src/design/Card/index.stories.tsx
- src/design/Card/index.tsx
> Card Component

- package.json
- src/design/Separator/index.stories.tsx
- src/design/Separator/index.tsx
- yarn.lock
> Separator component

- package.json
- src/design/ContextMenu/index.stories.tsx
- src/design/ContextMenu/index.tsx
- yarn.lock
Basic UI Design and stories on ContextMenu component
> DIR-340 ContextMenu Component

- package.json
- src/design/RadioGroup/index.stories.tsx
- src/design/RadioGroup/index.tsx
- yarn.lock
Basic UI design for Radio Group component
> DIR-341 Radio Group

- package.json
- src/design/Appshell/index.stories.tsx
- src/design/Tabs/index.stories.tsx
- src/design/Tabs/index.tsx
- src/pages/namespace/Workflow/index.tsx
- yarn.lock
Basic UI and stories for the Tabs component
> DIR-85 Tabs component

- .dockerignore
- .github/workflows/build-docker.yaml
- Dockerfile
This PR adds:
- Add build and publish docker images on PRs
> Add build and publish docker images on PRs

- src/design/Appshell/index.stories.tsx
- src/design/Appshell/index.tsx
Preview at https://direktiv-ui-refs-heads-porleaaron28-dir-653-sticky-breadcrumb.direktiv.dev/
> [DIR-653] Maintop to be sticky

- .github/workflows/build-docker.yaml
- .github/workflows/playwright.yml
This PR disables broken CI workflows temporary
> Disable CI Workflows

- .github/workflows/build-docker.yaml
> Redo printing deployment URL

- .github/workflows/build-docker.yaml
> Fix Header forwarding

- src/design/Button/index.stories.tsx
- src/design/Button/index.tsx
- src/design/ButtonBar/index.stories.tsx
- src/design/ButtonBar/index.tsx
- src/pages/namespace/Instances/components/Filters/index.tsx
- src/pages/namespace/Settings/index.tsx
1. update the Button component to have props asLabel
2. update the ButtonBar component to handle the "label" children.
3. update the stories for Button and ButtonBar component
1. Does label have Hover effect as I have removed the click effect from button in case of asLabel
2. Any other UI requirements in case of label?
> [DIR-709] buttonbar needs to support label, update button component to have asLabel props

- src/design/InputWithButton/index.stories.tsx
- src/design/InputWithButton/index.tsx
- src/pages/namespace/Instances/components/Filters/RefineTime.tsx
- src/pages/namespace/Instances/components/Filters/TextInput.tsx
:rocket: preview: https://direktiv-ui-refs-pull-437-merge.direktiv.dev/
* Uses InputWithButton to add a submit button to the time input in the instance filters
* Ditto for the TextInput for filtering by name
* Fixes a serious bug I noticed by chance: The guard I had previously added to check that time values are not undefined also prevented them having a value of "0".
> [DIR-705] Add submit buttons to inputs in filters

- .github/workflows/build-docker.yaml
- .github/workflows/playwright.yml
> Add selfhosted runner

- src/design/Toast/index.tsx
1.  Remove padding and margin around Toast 
1. Do we have use case of "toasts list", many toasts on one screen ?
> [DIR-734] Toast too big

- frontend/main.go
- frontend/server/config.go
> changed config

- conf/nginx.conf
Bugfix syntax error in nginx.conf
> Bugfix syntax error in nginx.conf

- Dockerfile.base
- Makefile
- frontend/server/config.go
- frontend/server/error.go
- Makefile for ee and os builds
- go config changes
> change config and makefile for ee build

- frontend/server/config.go
default setting change for backend server
> change config default

- src/pages/namespace/Services/Detail/Create.tsx
- src/pages/namespace/Services/List/Create.tsx
- src/pages/namespace/Services/List/Row.tsx
This PR fixes "[Long commands should be shortened](https://linear.app/direktiv/issue/DIR-811/long-commands-should-be-shortened)"
> [DIR-811] handle long commands

- src/pages/namespace/Explorer/Tree/NewWorkflow/templates.tsx
This PR adds `direktiv_api: workflow/v1` to all of our workflow templates. I created a workflow from each of the templates afterward.
> [DIR-840] add direktiv_api: workflow/v1 to all workflow templates

- src/pages/namespace/Events/History/ViewEvent.tsx
- src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
- src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
- src/pages/namespace/JqPlayground/index.tsx
- src/pages/namespace/JqPlayground/utils.ts
- src/pages/namespace/Services/Detail/Create.tsx
- src/pages/namespace/Services/List/Create.tsx
- src/util/__tests__/utils.test.ts
- src/util/helpers.ts
This PR fixes:
- [Input and Output on the instance page is not pretty printed](https://linear.app/direktiv/issue/DIR-815/input-and-output-are-not-pretty-printed)
- [View events is not pretty printed](https://linear.app/direktiv/issue/DIR-813/view-events-is-not-pretty-printed)
Note: dir-615 in the branch name is a typo and should be 815
> [DIR-813] [DIR-815] Pretty print json

- Makefile
Changing default image name from ui to frontend
> change default image name

- src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
- src/pages/namespace/Settings/Variables/index.tsx
This PR adds an `onSuccess` calback to the variable delete mutation to close the modal.
> [DIR-893] - workflow variable - delete modal did not close

- .github/workflows/build-docker.yaml
- Dockerfile
Enable multiplatform image build
> Enable multiplatform image build

- .github/workflows/build-docker.yaml
- Dockerfile
- conf/entrypoint.sh
- conf/nginx.conf
- deploy.nomad
> Parameterize docker image

- src/design/Filepicker/index.stories.tsx
- src/design/Filepicker/index.tsx
Introducing a design for a new component called Filepicker
The basic functionality is a scrollable overlay with many items that opens upon button click.
> [DIR-946] Filepicker Component

- Dockerfile.dev
- src/index.tsx
- vite.config.ts
Fixes Firefox error
`Error: Minified React error #426; visit https://reactjs.org/docs/error-decoder.html?invariant=426 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`
> [DIR-969] fix lazy loading issue in ff 

- frontend/server/config.go
- frontend/server/route-manager.go
> added gateway routes

- Dockerfile.prod
- src/api/enterprise/session/query/ping.ts
- src/config/enterprise.ts
> Updated ping and logout

- public/locales/en/translation.json
- src/api/services/schema/services.ts
- src/pages/namespace/Explorer/Service/ServiceHelp.tsx
- src/pages/namespace/Explorer/Tree/NewService/config.ts
- src/pages/namespace/Explorer/Tree/NewService/index.tsx
- src/pages/namespace/Services/List/Row/EnvVariables.tsx
- src/pages/namespace/Services/List/Row/index.tsx
This PR adds env variables to the services in the UI
- added envs to the form
- added envs to the example tooltip
- display envs in the services list
**Demo:**
https://github.com/direktiv/direktiv-ui/assets/121789579/040e8e6f-3943-4bca-bada-7d4a2e0dfd45
**This is how env variables look in the services list**
> [DIR-859] [DIR-966] add environment variables to services

- public/locales/en/translation.json
- src/api/gateway/schema.ts
- src/componentsNext/Breadcrumb/ExplorerBreadcrumb/BreadcrumbSegment.tsx
- src/componentsNext/NamespaceSelector/index.tsx
- src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
- src/pages/namespace/Gateway/Routes/Table/Row/Methods.tsx
- src/pages/namespace/Gateway/Routes/Table/Row/Plugins.tsx
- src/pages/namespace/Gateway/Routes/Table/Row/index.tsx
- src/pages/namespace/Services/List/Row/index.tsx
- src/pages/namespace/Settings/Registries/index.tsx
While reviewing [DIR-943](https://linear.app/direktiv/issue/DIR-943) I made some suggestions directly in the code, because it will be easier to just review these changes as a new PR instead of commenting on PRs that are already merged.
These are primarily small typos and similar stuff.
> [DIR-943] Postponed review fixes

- Dockerfile.prod
- conf/prod/entrypoint.sh
- conf/prod/nginx.conf
> update Docker for prod
