- src/layouts/explorer/workflow/revisionTab.js
Closes #226
Revisions with a traffic weight of `0` will no longer display the `Traffic amount` element.
> Closes #226

- package.json
- src/layouts/events/index.js
- yarn.lock
Fixed events table using receivedAt instead of updatedAt  for time row.
> Event listener timestamps updated

- src/layouts/explorer/index.js
Fixes: https://github.com/direktiv/direktiv-ui/issues/251
> noop template added back as default

- src/layouts/events/index.js
- src/layouts/explorer/index.js
- src/layouts/instances/index.js
- src/layouts/monitoring/index.js
Change the pagination count to 10 for instances, explorer and to 8 for events
> added item count for explorer, events, instances

- src/layouts/mirror/index.js
Soft and hard sync removed from mirror info page and replaced with just sync
> git: soft and hard sync removed and replaced with just sync

- Dockerfile
- conf/nginx.conf
We are moving from our reactjs-embeded server to nginx on release 0.7. The depencey to our legacy webserver: https://github.com/direktiv/reactjs-embed is removed in this PR and is replaced with the OTS solution Nginx.
Reason for removal:  The original reason for reactjs-embed (Configuration injection into built javascript files) is no longer required.
https://github.com/direktiv/direktiv/issues/619
https://github.com/direktiv/direktiv-ui-ee/pull/16
https://github.com/direktiv/direktiv-ui/pull/323
https://github.com/direktiv/direktiv-charts/pull/24
> Ngnix added to Dockerfile to replace webserver

- src/pages/namespace/Settings/Registries/index.tsx
- src/pages/namespace/Settings/Secrets/index.tsx
- src/pages/namespace/Settings/Variables/Edit.tsx
- src/pages/namespace/Settings/Variables/MimeTypeSelect.tsx
- src/pages/namespace/Settings/Variables/index.tsx
Changes:
* Lists on settings page are not rendered before they are fetched to avoid spinners / layout shifts 
* When editing a variable, the editor is not rendered before the content is fetched, and the mimeTypeSelect has a loading spinner.
> [DIR-627] Settings: loading states

- src/pages/namespace/Settings/Variables/Edit.tsx
After DIR-542 has been merged, the Editor components used for creating secrets and variables no longer focus on mount. This is as intended, because the name input should be focused first.
When editing variables, it makes sense to focus the Editor right away. This PR adds that behavior.
Preview at https://direktiv-ui-refs-pull-405-merge.direktiv.dev/sebxian/settings
> [DIR-630] settings editor focus

- e2e/explorer/workflow/active.spec.ts
- e2e/explorer/workflow/revisions/revisionsDetail.spec.ts
This might improve the flaky tests:
I have added `{ waitUntil: "networkidle" }` to some tests that occasionally fail.
In the trails (screenshots), it seemed the page wasn't fully loaded after a `page.reload`, before the failed assertion took place.
The CI pipeline tests for this PR should already tell us if this helped.
> Fix test timing (waitUntil networkidle)

- .eslintrc.js
- e2e/explorer/workflow/revisions/revisionsDetail.spec.ts
- e2e/explorer/workflow/revisions/revisionsList.spec.ts
- e2e/explorer/workflow/utils.ts
- e2e/settings/index.spec.ts
- e2e/utils/testutils.ts
- src/pages/namespace/Explorer/Workflow/Revisions/Detail/index.tsx
- src/pages/namespace/Settings/Variables/Edit.tsx
This fixes several problems which resulted in flaky tests:
* When loading the revisions detail page `namespace/explorer/workflow/revisions` directly (as opposed to navigating there), sometimes in Webkit browsers (e.g. Safari) the editor's content is not loaded. This was solved by adding an early return to the revisions detail page, so the editor is not loaded before the content is fetched.
* Changed the way that the content of the monaco editor is checked. The new method reads the value of the "textbox" element directly and also tries again until the test condition is true (previously reading the textbox value failed when the editor had not finished initializing). 
* Checks of the editor's content have been added to tests where it was visible, but not tested before.
* Some click events …
> [DIR 639] Fix flaky tests

- src/App.css
- src/design/Alert/index.tsx
- src/design/Appshell/index.stories.tsx
- src/design/Checkbox/index.stories.tsx
- src/design/Command/index.stories.tsx
- src/design/Command/index.tsx
- src/design/ContextMenu/index.tsx
- src/design/Dialog/index.tsx
- src/design/Dropdown/index.tsx
- src/design/Editor/theme-dark.ts
- src/design/Editor/theme-light.ts
- src/design/JSONschemaForm/index.tsx
- src/design/NavigationLink/index.tsx
- src/design/Pagination/index.tsx
- src/design/Select/index.tsx
- src/design/Tabs/index.tsx
- src/design/Toast/index.tsx
- src/design/Tooltip/index.tsx
- src/pages/namespace/Explorer/Tree/index.tsx
- src/pages/namespace/Explorer/Workflow/Active/WorkflowEditor.tsx
- src/pages/namespace/Explorer/Workflow/Revisions/Detail/index.tsx
- src/pages/namespace/Explorer/Workflow/Revisions/Overview/List/index.tsx
- src/pages/namespace/Explorer/Workflow/Revisions/Overview/TrafficShaping/index.tsx
- src/pages/namespace/Explorer/Workflow/Revisions/Overview/index.tsx
- src/pages/namespace/Instances/List/index.tsx
- src/pages/namespace/Settings/Broadcasts/index.tsx
- src/pages/namespace/Settings/Registries/index.tsx
- src/pages/namespace/Settings/Secrets/index.tsx
- src/pages/namespace/Settings/Variables/index.tsx
- src/pages/namespace/Settings/index.tsx
This PR is best reviewed with the [old](https://direktiv-ui-refs-heads-feature-redesign.direktiv.dev/stefan/explorer/tree) and [new](https://direktiv-ui-refs-heads-stefankracht-dir-683-design-tweaking.direktiv.dev/stefan/explorer/tree) version opened in two browser tabs. The goal is to make the base color much darker as it was before. The old version has very low contrast and looks very pale. The new version is still not perfect, but I think a good iteration in the right direction.
[Changing the base color](https://github.com/direktiv/direktiv-ui/pull/418/commits/4ed72a68dc647d9505c62a07517c815429fa14c7) forced me to change a lot of colors in other files to either also change the color there or keep the appearance as it was before and not inherit that change (e.g. I wanted to keep all …
> [DIR-683] design improvements

- .env.example
- e2e/explorer/workflow/active.spec.ts
- e2e/explorer/workflow/diagramEditor.spec.ts
- e2e/explorer/workflow/revisions/revisionsDetail.spec.ts
- e2e/explorer/workflow/revisions/revisionsList.spec.ts
- e2e/explorer/workflow/revisions/trafficShaping.spec.ts
- e2e/explorer/workflow/run.spec.ts
- e2e/instances/list/index.spec.ts
- e2e/setup/auth.ts
- e2e/utils/broadcasts.ts
- e2e/utils/namespace.ts
- e2e/utils/node.ts
- e2e/utils/registries.ts
- e2e/utils/revisions.ts
- e2e/utils/secrets.ts
- e2e/utils/testutils.ts
- e2e/utils/variables.ts
- playwright.config.ts
- src/pages/namespace/Settings/index.tsx
This enables playwright to run against an API that requires an authentication token.
This is based on the branch `stefankracht/dir-716-remove-revision-id-from-the-frontend` because that already fixes some tests. So the PR is set up to merge into that branch.
What I did:
* Add headers to all requests originating in playwright (mostly for creating and cleaning up test data).
* Add a local storage context that will be applied to the front-end app when executed in playwright.
* Updated the .env.example (variable to set for using token in e2e tests)
* There is a comment in the new file `e2e/setup/auth.ts` explaining my approach to set up the browser context in playwright.
Notes:
* All tests ran without errors against the version deployed on the dev-server (please confirm during review that …
> Add API token authentication to playwright

- .env.example
- .github/workflows/playwright.yml
- e2e/explorer/workflow/active.spec.ts
- e2e/explorer/workflow/diagramEditor.spec.ts
- e2e/explorer/workflow/revisions/revisionsDetail.spec.ts
- e2e/explorer/workflow/revisions/revisionsList.spec.ts
- e2e/explorer/workflow/revisions/trafficShaping.spec.ts
- e2e/explorer/workflow/run.spec.ts
- e2e/instances/list/index.spec.ts
- e2e/setup/auth.ts
- e2e/utils/broadcasts.ts
- e2e/utils/namespace.ts
- e2e/utils/node.ts
- e2e/utils/registries.ts
- e2e/utils/revisions.ts
- e2e/utils/secrets.ts
- e2e/utils/testutils.ts
- e2e/utils/variables.ts
- package.json
- playwright.config.ts
- public/locales/en/translation.json
- src/api/instances/schema.ts
- src/pages/namespace/Instances/List/Row.tsx
- src/pages/namespace/Instances/List/index.tsx
- src/pages/namespace/Settings/index.tsx
- yarn.lock
As the api will no longer provide the revision at the instance endpoint (`as: "workflow:latest` changed to `as: "workflow`) we need to remove the column.
This also makes the code a lot cleaner since we now always link to the latest revision.
I have adjusted the e2e tests, but without running them. It would be great if @sebxian could run the tests locally against an api that doesn't require an api token.
> [DIR-716] remove revision from the instance list

- public/locales/en/translation.json
- src/api/namespaces/__tests__/schema.test.ts
- src/api/namespaces/mutate/createNamespace.ts
- src/api/namespaces/schema.ts
- src/api/tree/schema.ts
- src/componentsNext/NamespaceCreate/InfoTooltip.tsx
- src/componentsNext/NamespaceCreate/index.tsx
- src/design/InputWithButton/index.tsx
* Added new tab to namespace create dialog that makes it possible to create mirror.
* Depending on the namespace type (mirror or simple namespace), and mirror auth method (none, ssh, token), the validation schema changes so only valid data can be submitted. 
* Updated the NodeSchema to be compatible with latest API changes (without this, rendering of non-workflow files in a mirror can fail). There is still work to be done on rendering non-workflow files correctly, but that should be in the scope of another ticket (DIR-475).
* Aaron has already created an InfoTooltip component under `src/componentsNext/NamespaceCreate/InfoTooltip.tsx` in https://github.com/direktiv/direktiv-ui/pull/428/, I think I will use that one when it has been merged and remove the one under …
> DIR-471 Add mirror form to namespace create dialog

- e2e/instances/list/index.spec.ts
- src/design/TooltipCopyBadge/index.stories.tsx
- src/design/TooltipCopyBadge/index.tsx
- src/pages/namespace/Instances/List/Row.tsx
This adds a design component and corresponding storybook story, as discussed in person with @stefan-kracht .
I decided the name should start with "Tooltip" after all, because it requires to be wrapped in a TooltipProvider.
We discussed making the tooltip optional in the future, but my current thoughts on this are: It might make things complicated (regarding the requirement of having a parent TooltipProvider), and my main reason to componentize this was the boilerplate code required for the tooltip. For use cases where we just need a badge without tooltip, I am not sure using a component (other than `design/Badge` is justified.
I have added the component to the instances list and updated the e2e tests accordingly (because test-ids have changed).
> Tooltip Copy Badge

- public/locales/en/translation.json
- src/api/registries/mutate/testConnection.ts
- src/api/registries/schema.ts
- src/pages/namespace/Settings/Registries/Create.tsx
- src/pages/namespace/Settings/Registries/Create/TestConnectionButton.tsx
- src/pages/namespace/Settings/Registries/Create/index.tsx
This PR is an add-on to [this PR](https://github.com/direktiv/direktiv-ui/pull/443) to avoid merge conflicts. It implements the Test Connection Button on the registry page.
**[Preview 🚀](https://direktiv-ui-refs-pull-445-merge.direktiv.dev/)**
https://github.com/direktiv/direktiv-ui/assets/121789579/c04592d4-833d-4faf-914c-2153bd40b9ba
While developing this feature, I found out that the API behind this button is more a validation and not a real connection test (e.g. any url starting with https://hub.docker.com passes the connection test, username and password does not seem to matter). We should discuss, whether we should just mimic this behavior on the client and make this a real validation and not implying to check the credentials and the actual existent of the repo.
- …
> [DIR-622] test registry credentials

- public/locales/en/translation.json
- src/api/registries/mutate/testConnection.ts
- src/api/registries/schema.ts
- src/pages/namespace/Settings/Registries/Create.tsx
- src/pages/namespace/Settings/Registries/Create/TestConnectionButton.tsx
- src/pages/namespace/Settings/Registries/Create/index.tsx
- src/pages/namespace/Settings/Registries/index.tsx
- src/pages/namespace/Settings/Secrets/Create.tsx
- src/pages/namespace/Settings/Secrets/index.tsx
- src/pages/namespace/Settings/Variables/Create.tsx
- src/pages/namespace/Settings/Variables/Edit.tsx
- src/pages/namespace/Settings/Variables/index.tsx
- src/pages/namespace/Settings/components/CreateItemButton.tsx
**[Preview 🚀](https://direktiv-ui-refs-pull-443-merge.direktiv.dev/)**
This PR adds a client side search to secrets, registries and variables ![CleanShot 2023-08-10 at 15 08 02@2x](https://github.com/direktiv/direktiv-ui/assets/121789579/a022fc3f-511a-4018-b8ec-0d4add991151)
- Made header of secrets, registries and variables responsive
- I changed every "+" Button to be like "+ Create Variable". It looks better on mobile, because the button is much bigger. And I even like it better to very explicit, and it also matches "+ send new event" button on the new events page ![CleanShot 2023-08-10 at 14 25 04@2x](https://github.com/direktiv/direktiv-ui/assets/121789579/d10aea1b-60ff-49b4-92d1-d1ef06fc6cf9)
- Changed modal button from primary variant to default variant. I noticed that we never use …
> [DIR-626] add pagination and search to settings page

- public/locales/en/translation.json
- src/api/tree/mutate/toggleLive.ts
- src/api/tree/schema.ts
- src/pages/namespace/Explorer/Workflow/index.tsx
[Preview](https://direktiv-ui-refs-pull-448-merge.direktiv.dev/)
This adds the ability to turn the workflow active / inactive.
It's implemented on top of the branch for the workflow settings page in PR #447.
I made the dropdown trigger variant="primary" as well, but that doesn't look good when the main button is inactive:
So I changed the dropdown trigger to "outline", but only when the other button is inactive. It's not 100% logical to have the dropdown button active in the second example, but that way it blends in naturally with the main button.
> [DIR-209] set live status on workflow

- src/api/tree/query/mirrorInfo.ts
- src/pages/namespace/Services/Detail/Create.tsx
- src/pages/namespace/Services/List/Create.tsx
This PR will reverse the order of the mirror activities to make the newest appear on top. 
Before:
https://github.com/direktiv/direktiv-ui/assets/121789579/8994eae6-b994-4dfb-a420-36240e7383fa
After:
https://github.com/direktiv/direktiv-ui/assets/121789579/8b95ce28-dc8d-4de0-b095-d6dbbeb31f0b
--- 
Follow-up ticket
- [DIR-833: This behavior should be handled by the backend](https://linear.app/direktiv/issue/DIR-833/reverse-the-order-of-mirror-activities)
> [DIR-821] reverse mirror activities

- e2e/explorer/workflow/run.spec.ts
- src/pages/namespace/Explorer/Workflow/Active/WorkflowEditor.tsx
- src/pages/namespace/Services/Detail/Create.tsx
- src/pages/namespace/Services/List/Create.tsx
This PR will disable the run button when the editor has unsaved changes.
https://github.com/direktiv/direktiv-ui/assets/121789579/74bdaa68-8d98-4c31-80fe-74a03d88cb19
Running a workflow when the user has unsaved changes can create problems. The user may not even be aware that their changes haven't been saved. For example, if the user attempts to save their work but encounters a syntax error, the changes will not be saved at that moment. If the user doesn't notice the error and proceeds to run the workflow, it will execute in an unexpected state. Additionally, all previous changes that were not saved will be lost.
> [DIR-817] disable the run button when the the editor has unsaved changes

- src/pages/OnboardingPage.tsx
Description from the ticket
> If I delete the last namespace the UI stays on the namespace UI. It even shows in the breadcrumb but it should go to the "create namespace" page.
- In `src/api/namespaces/mutate/deleteNamespace.ts`, in the `onSuccess` callback we invalidate the namespaces list after the namespace was deleted. 
- The user will then be redirected to the landingpage (this is triggred in line `38` in `src/pages/namespace/Settings/DeleteNamespace/Delete.tsx`)
- On the landingpage, a `useEffect` will see that there are some namespaces in the store and redirect to the first one (because localstorage has no prefered namespace stored after the delete action)
- We invalidate the cache when a namespace is deleted, which triggered a refetch
- When the `useEffect` on the landing page …
> [DIR-843] Deleting last namespace behaviour is incorrect

- src/design/Button/index.tsx
- src/pages/namespace/Explorer/Workflow/Revisions/Detail/index.tsx
- src/pages/namespace/Instances/Detail/Header/index.tsx
- src/util/router/pages.tsx
See DIR-814 for details.
This fixes a bug that only appeared in production, where the "Open workflow" button on the instances detail page didn't work. In development mode, there was no issue with the button.
I removed (commented) the code in src/design/Button/index.tsx that checks whether the child is a Link (`isLinkComponent`). Depending on what we decide, we should delete it completely (or fix it).
In production, this check isn't successful in the instance page for the "Open Workflow" button. I could not debug it completely because the zod error messages are very hard to read.
Playwright tests ran successfully locally so I don't think my changes broke anything (but a few of the tests seem to be a bit flaky).
We should discuss whether we should: (a) use the Button with my fix in the …
> [DIR-814] Fix "Open workflow" button on instances page (was bugged in production only)

- src/api/services/index.ts
- src/api/services/query/revision/pods/getLogs.ts
This fixes an issue where logs from pods did not show up in the UI. The problem was that the `useQuery` subscribed to a cache key with a namespace field in it and the streaming provider wrote the data in a cache that did not have the namespace in the cache key. 
This did not show up as a TS issue, since the namespace was not mandatory in the cache key. I guess this was either typed as optional by mistake, or it might come from an earlier implementation version.
I changed the following:
- namespace is now mandatory (there are now TS errors, so this should be fine)
- `usePodLogsStream` now writes to the cache key with the namespace in it
After this change, I get logs on both pages, the services and the workflow services
> [DIR-887] no logs for pods

- package.json
- src/api/schema.ts
- src/api/streaming.ts
- src/pages/namespace/Instances/Detail/Main/Logs/ScrollContainer.tsx
- src/pages/namespace/Mirror/Activities/Detail/Logs/ScrollContainer.tsx
- src/pages/namespace/Monitoring/Logs/Scrollcontainer.tsx
- src/pages/namespace/Services/Detail/Revision/Pods/ScrollContainer.tsx
- src/util/helpers.ts
- yarn.lock
This PR addresses a problem with our `@tanstack/react-virtual` implementation
- Occurs in firefox on linux
- the problem grows, with the length of each log line (the longer the line, the more unpredictable the log item height)
- this also fixes an issue where mirror logs could failed validation because of a "new" loglevel named "warn". Like e.g. `Detected a possible deprecated workflow variable definition with an invalid name at: conditional-states/README.md`
> [DIR-855] [DIR-746] [DIR-888] - fix scroll virtualization issue

- public/locales/en/translation.json
- src/pages/namespace/Mirror/Activities/index.tsx
This PR was ment to fix an issue where mirror logs were empty. This issue turned out to be invalid, but I found and fixed this on the way:
Show "No activities found" when mirror activities are empty.
> [DIR-895] - show "No activities found" when mirror activities are empty

- e2e/errorPage.spec.ts
- src/util/router/ErrorPage.tsx
This PR fixes an issue on the error page, whre the "Go to homepage" link is not working. After we introduced the `isAnchor` property to links that look like buttons, we did not add the prop to this button.
I also added e2e tests for the error page in general to cover this bug and basic functionality of the error page.
> [DIR-897] - "Go to homepage" link does not work on the 404 page

- src/api/version/schema.ts
Updates the version schema to only use the fields that we actually need. This will prevent the UI to throw an error when, flow or functions are not set.
> [DIR-911] update versions schema

- src/api/tree/schema/node.ts
The gateway config will improve a new file type called "endpoint". This is already implemented in branch `main` of the api repository.
To create a new "endpoint" file, you have to create a namespace called "gateway_namespace". This namespace will have additional features.
Then, create a workflow.yaml file with this content (I think only the first line is really relevant for now):
```
direktiv_api: "endpoint/v1"
method: "POST"
plugins:
- type: "router_weighted"
config:
backends:
- namespace: "my_namespace"
workflow: "/path/to/workflow.yaml"
weight: 90
- namespace: "my_namespace"
workflow: "/path/to/workflow2.yaml"
weight: 10
```
The API will then create an "endpoint" file, but currently the ui will throw an error when parsing the resonse, because the file type isn't in the zod enum.
This …
> [DIR-933] endpoint file type

- src/api/tree/schema/node.ts
- src/api/tree/utils.ts
- src/design/Editor/utils.ts
- src/pages/namespace/Explorer/Tree/FileRow/ConditionalLink.tsx
This PR adds the type consumer to the file type schema to prepare for the gateway release.  It also introduces an icon for "endpoint" and "consumer" files and makes them previewable
> [DIR-967] add consumer to file types

- .github/workflows/build-docker.yaml
- .github/workflows/playwright.yml
- .github/workflows/storybook.yml
- .github/workflows/testbuild.yml
This cleans up our current CI pipeline:
- disabled playwright: Playwright test in CI were not valid anymore because the API in CI was never up-to-date. We are switching to manual testing before every PR merge. A possible solution could be spinning up the api with the docker driver which might be lightweight enough to run in an action
- disable docker build (preview server has been wiped)
> [DIR-1036] clean up ci

- e2e/explorer/workflow/diagramEditor.spec.ts
- src/pages/namespace/Explorer/Workflow/Active/WorkflowEditor.tsx
This PR fixes a bug in the workflow editor where the most recent changes got lost when the user switched to the diagram view and then back to the code editor view.
The bugfix itself was actually very simple, but I had to introduce a `useEffect` as well to handle a side effect that occurs when the user clicks the "revert to previous revision" (luckily, this was covered by a test and was probably the root cause of why the internal state was designed this way). 
I also introduced an e2e to cover the correct behavior.
All e2e test are passing with the api at commit `46e73a0de70f9e0bb75319300933916a08a52517`
> [DIR-912] Switching between views in workflow view wipes content

- .env.example
- e2e/errorPage.spec.ts
- e2e/explorer/index.spec.ts
- e2e/settings/deleteNamespace.spec.ts
- playwright.config.ts
I had several problems with the e2e tests on my laptop. This fixes them (only the diagramEditor tests are still a bit flaky, but I can live with that for now).
As discussed in person, it is probably best to consider my new config values as "safe" and use them as our new default.
It is always a bit hard to be sure with playwright, but I think the main issues were:
- Multiple test runners in parallel were causing lots of timeouts, so I restricted "runners" to 1 in the config.
- the original behavior can be restored by setting an ENV variable
- Playwright's built in test server needs a timeout to work reliably. I cannot make sense of the value itself (I just set it to the documented default), I only know that there are problems without setting this value here.
- I also set the timeout for …
> Fix e2e timing problems

- e2e/events/listeners.spec.ts
Since we are no longer testing against an outdated API, I unskipped one test for an issue that was already fixed on main.
e2e tests ok against 398481d6.
> Unskip test

- e2e/usermenu.spec.ts
This fixes the e2e test for the user menu.
It failed on my system and when investigating, I found that no namespace is created before performing this test. So if performed in isolation, the onboarding page will be rendered and the user menu will not be accessible. Probably the test didn't fail in the past because namespaces from other tests existed.
> Fix e2e test for usermenu
